### ISSUE TITLE
Add the possibility to create a http server

### ISSUE THREAD

**Issue by Mrgaton** [dippyshere/stw-daily#42]
It would be nice if you could turn on an http server even though it always returns a message to be able to host it from replit 24/7

**Comment by dippyshere** [comment]
Unfortunately, this run configuration is unsupported by both us and Replit without upgrading your plan. For an always online option, it is recommended you use https://discord.com/application-directory/757776996418715651, and if you'd like to see any additions or changes you've made be incorporated here and on STW Daily, you can create a pull request.
